### ISSUE TITLE
Perder o Ganar reinicia el juego y no manda al menu

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#100]
Proyecto: Python/mines.py
Version: 3
Plataforma: Pc - Windows 10 64b
Gravedad: min
Descripcion: Si se crea un juego de 8x8 con 6 minas, y se pierde o se gana, se reinicia el juego con las mismas configuraciones (8x8 con 6 minas) en vez de salir al menu,
Paso a paso:
1.Abrir un juego
2.Setear con parametros a eleccion 
3.perder o ganar 
Tasa de reproduccion: 100%

**Comment by didierrenardub** [comment]
Won't fix; no hay menú del juego sino que el usuario es libre de realizar la acción que quiera cuando quiera. Por eso, hacemos que la experiencia del usuario sea que se vuelve a iniciar una nueva partida con los mismos parámetros, para fomentar que vuelva a jugar.
