### ISSUE TITLE
Regla del primer tiro sin minas, no se cumple

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#102]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso:  Creo una partida. Tablero pequeño "3 2 1".  En el primer intento que golpea la mina, se pierde el juego. No cumple con la regla de que el primer tiro tiene que ser libre de minas.

![image](https://user-images.githubusercontent.com/48370383/55268205-6370f600-5266-11e9-82fc-7cf2d3efc752.png)

**Comment by didierrenardub** [comment]
Won't fix, me baso en la versión original del buscaminas!
