### ISSUE TITLE
Sin desafios diarios

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#120]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso:  basandonos en el año 2019, al no tener objetivos diarios, hace que el juego se torne aburrido y en aspecto economico para la empresa que lo crea, si no consigue usuarios, no rinde, por ende 0$. 

Ejemplo de desafio: Despejar el tablero sin detonar mas de 2 minas.

**Comment by didierrenardub** [comment]
Won't fix. Mucho trabajo!
