### ISSUE TITLE
Crashea tras desacatar instrucciones 

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#13]
Proyecto: mines.py
Versión: --
Plataforma: PC. S.Op: Windows 7 64bits
Gravedad: Critical
Título: Crashea tras desacatar instrucciones 
Descripción: tras inicializar con help,(1) si se pone cualquier otra cosa que no sea game y los 3 numeros correspondientes crashea. (2) si no se siguen las instrucciones para jugar exactamente crashea. Por ejemplo si no pongo espacio entre los numeros que le paso a "show"
Tasa de reproducción: 10/10
Paso a paso: 1) abro el .py 2) implemento comando help 3) escribo cualquier otra cosa que sea game y los 3 numeros correspondientes crashea.
(1)
![image](https://user-images.githubusercontent.com/48369913/54872277-4046d200-4da0-11e9-8949-3e3e9a9ff118.png)

(2) si no escribis show + numero + numero  con espacios en el medio crashea. Es decir, otra vez crashea si no acatas las instrucciones exactamente como el help te indica.
![image](https://user-images.githubusercontent.com/48369913/54872285-4d63c100-4da0-11e9-8a8d-a86563e2767c.png)

**Comment by didierrenardub** [comment]
Mismo problemita aquí con el título. Podría ser algo como "Crash al no pasar suficientes parámetros a un comando"; "desacatar instrucciones" puede referirse a cualquier cosa!
