### ISSUE TITLE
Tiene un solo modo de juego. Tableros predeterminados inexistentes

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#133]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso: trae un solo modo de juego sin puntuacion. Hay que crear constantemente los tableros para jugar, lo cual se torna repetitivo. No tiene tableros predeterminados. Sin incentivos.

**Comment by didierrenardub** [comment]
Won't fix, me atengo al buscaminas tradicional.
