### ISSUE TITLE
No tiene politicas de privacidad, ni terminos de condiciones de uso.

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#135]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso: no se especifica casi nada de informacion acerca del programa. Quien lo creo. Su copyright. Si se puede contactar con alguien en caso de fallas.

**Comment by didierrenardub** [comment]
Won't fix!
