### ISSUE TITLE
Tipeo de Help en vez de Menu.

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#136]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso: la palabra help deberia ser de "ayuda" para resolver alguna duda que tiene el usuario acerca del juego y no para mostrar todo el menu cada vez que deseo iniciar nuevamente. En todo caso para que sea mas intuitivo habria que poner m/menu.

**Comment by didierrenardub** [comment]
Not a bug. No hay un "menú" para el juego sino comandos que pueden ser ejecutados en cualquier instancia. Por tal motivo es que hay un comando de ayuda y no hay menú alguno.
