### ISSUE TITLE
Sin posibilidad de compartirlo a traves de redes. Solo mail,pendrive o nube.

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#139]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso: la unica forma de compartir este juego es pasando en un pendrive el archivo de mines.py o por mail. No muestra la posibilidad de mandarlo en linea a cualquier usuario. Por ej: Skype, whatsapp, etc. Sin simbolo de "compartir".

**Comment by didierrenardub** [comment]
Won't fix - ya sería demasiado jaja
