### ISSUE TITLE
No pide vincular ningun tipo de mail.

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#142]
1-Proyecto de la falla encontrada: mines.py
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso: no pide vincular mail para sincronizar archivos ni documentos  ni configuracion. Lo bueno es que deja que cualquier tipo de usuario pueda jugar sin limitaciones.

**Comment by didierrenardub** [comment]
Won't fix, también es demasiado para esto!
