### ISSUE TITLE
no mostrar los numeros 

### ISSUE THREAD

**Issue by franciscoMigliardi24** [didierrenardub/ub_testing#144]
proyect: mines.py
version: 2.0
plataforma: PC

gravedad: medium

al ingresar unas coordenadas de un espacio vacio, este muestra todos los espacios vacios los cuales esta tocando, pero no los numeros que tocan este dicho espacio.

en la foto se puede ver que ambos conjuntos estan con "#" 

![mines](https://user-images.githubusercontent.com/48457889/55409945-5dfefe80-5539-11e9-93c9-d542fc2ec20e.png)

**Comment by didierrenardub** [comment]
Hola Francisco! El título no es del todo claro; optaría por algo como "al mostrar un vacío, no se muestran los números adyacentes" o similar.
