### ISSUE TITLE
mayor cantidad de minas

### ISSUE THREAD

**Issue by franciscoMigliardi24** [didierrenardub/ub_testing#146]
proyect: mines.py
version: 2.0
plataforma: PC

gravedad: medium

al ingresar mayor cantidad de minas que de espacios el juego se tilda siendo imposible siquiera entrar al menu

![mines2](https://user-images.githubusercontent.com/48457889/55410388-280e4a00-553a-11e9-9a24-dc71cb4b7f7f.png)

**Comment by didierrenardub** [comment]
Nuevamente, el título no es muy descriptivo; tendría que ser algo así como "Crear partida con más minas que casilleros resulta en freeze"
