### ISSUE TITLE
Setear el tablero

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#15]
Proyecto: mines.py
Versión: --
Plataforma: PC. S.Op: Windows 7 64bits
Gravedad: Medium
Título: Setear el tablero con valores negativos
Descripción
 Permite poner valores negativos en el tercer valor a asignar (count mine) al setear el tablero con "game". Ejemplo: game 5 -5 2. Te dice que el "2" no es válido en vez del "-5"
![image](https://user-images.githubusercontent.com/48369913/54872353-6ae55a80-4da1-11e9-85de-bf6b2da30208.png)

**Comment by didierrenardub** [comment]
El título de este issue no es muy claro; en el interior pusiste "Setear el tablero con valores negativos", que sería un poco más descriptivo.
