### ISSUE TITLE
Ubicación de minas no se resetea al perder

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#155]
Proyecto: mines.py
Versión: 2
Plataforma: PC - Windows 64 bits
Título: Ubicación de minas no se resetea al perder
Gravedad: medium
Descripción: Al perder, el juego te pone a disposición un tablero con las mismas dimensiones que antes pero la minas sigue estando ubica igual. 
Paso a paso: abrir programa > setear game > show casillero > perdes > vuelve a mostrarte un tablero con la mismas dimensiones que antes (esto creo que es acertado) > la mina que te hizo perder está situada en el mismo lugar. 
Sugerencia: todas las minas deberían reubicarse automáticamente.
Tasa de reproducción: 100%

caso 1 : ![image](https://user-images.githubusercontent.com/48369913/55525647-4a05ea80-5668-11e9-862a-0a768e06f24b.png)

caso 2: 
![image](https://user-images.githubusercontent.com/48369913/55525849-14adcc80-5669-11e9-90ab-5198e8503f0d.png)

**Comment by didierrenardub** [comment]
La tasa de reproducción no es correcta, dado que no sucede el 100% de las veces. Lo estuve probando y es casualidad respecto de la disposición de las minas. Ergo, no es una falla.
