### ISSUE TITLE
Limitar la cantidad de minas en el tablero

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#156]
Proyecto: mines.py
Versión: 2
Plataforma: PC - Windows 64 bits
Titulo: Limitar la cantidad de minas en el tablero.
Descripción + sugerencia: No debería poder ponerse minas en todos los casilleros ya que pasarían dos situaciones que no deben darse en el juego
1)detonarias una mina al primer click
2)tendrías una mina rodeada de minas en sus 8 casilleros limitantes 
Tasa reproducción: 100% 

![image](https://user-images.githubusercontent.com/48369913/55674310-7a789f00-5889-11e9-93c8-6a2d59dfeec7.png)

**Comment by didierrenardub** [comment]
No lo puedo reproducir. Al intentar crear un tablero de 8x8 con 64 minas me indica que el máximo de minas es 12.
`g 8 8 64`
`Maximum mines allowed: 20% of board size (8x8 = 64, maximum = 12)`
