### ISSUE TITLE
Falta de menú al iniciar y concluir juego

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#157]
Proyecto: mines.py
Versión: 2
Plataforma: PC - Windows 64 bits
Título: Falta de menú al iniciar y concluir juego
Descripción + sugerencia: No hay menú. Al abrir el programa debería aparecer un menú que te indique como iniciar el juego. Y al terminar el juego, sea por perder o ganar, te vuelve a proporcionar automáticamente el mismo tablero de antes cuando debería sugerir algo de la índole ¿Desea continuar jugando con el mismo tablero o resetear su configuración/ quit?
Tasa reproducción: 100%

**Comment by didierrenardub** [comment]
Se arregla el problema de que no aparece nada al comenzar el juego, pero no el segundo problema.
Dado que el usuario puede invocar cualquier comando en cualquier momento, no se precisa de un menú. Por otro lado, el hecho de que se cree una nueva partida automáticamente es una comodidad para el usuario quien, si no desea jugar, puede simplemente salir.
