### ISSUE TITLE
Incómodo de visualizar

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#158]
Proyecto: mines.py
Versión: 2
Plataforma: PC - Windows 64 bits
Título: Incómodo de visualizar
Descripción: La interfaz, o carencia de interfaz, dificultan jugar ya que hay que forzar la vista. El tablero es muy pequeño, es decir, el tamaño de los caracteres. 
Tasa reproducción: -

**Comment by didierrenardub** [comment]
No se puede programáticamente cambiar el tamaño de la font de la consola, pero para facilitar la visión se le va a agregar color a los números.

La clave para ver que esto es posible era reportar la falla de que no hay mensaje de victoria o derrota. Intencionalmente puse esos mensajes en color para que quien testea se de cuenta de que es posible utilizar colores y así reportar que le falta claridad al juego.
