### ISSUE TITLE
El uso del comando show es impráctico 

### ISSUE THREAD

**Issue by beelanselm** [didierrenardub/ub_testing#159]
Proyecto: mines.py
Versión: 2
Plataforma: PC - Windows 64 bits
Título: El uso del comando show es impráctico 
Descripción: Cada vez que querés despejar un casillero, poner una flag, etc. hay que contabilizar para poder determinar las coordenadas y  usar el comando show. Esto implica una pérdida de tiempo y retraso al jugar, lo que hace al juego menos atractivo.
Tasa reproducción: 100%

**Comment by didierrenardub** [comment]
Se agregan coordenadas!
