### ISSUE TITLE
Usabilidad: El juego podria abrir en una ventana nueva

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#166]
Version: mines.py version 0.0.2al
Plataforma: Windows 10 64bit, Intel i7, 8GB RAM
Reproduccion del error: 100%
Gravedad: minal

Al crear un nuevo tablero, este se genera dentro de la misma consola.
Para mejorar la usabilidad seria ideal que el tablero se genere en una nueva ventana.

**Comment by didierrenardub** [comment]
Won't fix; me parece que puede provocar un infierno de ventanas abiertas. Alternativamente, podría limpiarse la pantalla. El problema con ello es que no va a permitir al usuario ver cómo terminó la partida anterior.
