### ISSUE TITLE
Reinicia mismo tablero despues de perder

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#167]
Version: mines.py version 0.0.2al
Plataforma: Windows 10 64bit, Intel i7, 8GB RAM
Reproduccion del error: 100%
Gravedad: medium

Al finalizar una partida, el juego automaticamente genera el mismo tablero.
Seria recomendable que se le pregunte al usuario si quiere seguir jugado y ofrecerle modificar el tablero a explorar.

**Comment by didierrenardub** [comment]
Won't fix. Siendo que el usuario puede elegir en cualquier momento qué hacer mediante el sistema de comandos, puede en cualquier momento crear un nuevo tablero con la configuración deseada o, alternativamente, abandonar la aplicación cuando lo desee usando el comando quit.
Crear un tablero con la misma configuración que la última partida es una conveniencia basada en que quizás al perder el usuario quiere repetir y superar el desafío.
