### ISSUE TITLE
Valores minimos de minas en eleccion de tablero

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#168]
Version: mines.py version 0.0.2al
Plataforma: Windows 10 64bit, Intel i7, 8GB RAM
Reproduccion del error: 100%
Gravedad: medium

Al generar un juego nuevo con valores menores a la altura y ancho y minas permitidos, avisa que debe tener mas minas. Si luego se modifica la cantidad de minas a un valor porcentual permitido, recien ahi el programa avisa que el alto y el ancho no son aptos. Deberia ser inverso. Primero avisar el ancho y la altura y luego el porcentaje de minas.

**Comment by didierrenardub** [comment]
No lo pude reproducir. Por favor enumerá el paso a paso.

**Comment by alehmaub** [comment]
Version: mines.py version 0.0.2al
Plataforma: Windows 10 64bit, Intel i7, 8GB RAM
Reproduccion del error: 100%
Gravedad: medium

![Capture](https://user-images.githubusercontent.com/38575000/55956087-82de2a80-5c39-11e9-976e-fa3f55db0fa4.JPG)
![Capture1](https://user-images.githubusercontent.com/38575000/55956088-82de2a80-5c39-11e9-8d2e-2b7f690e262c.JPG)
