### ISSUE TITLE
Se desplaza el menu

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#169]
Version: mines.py version 0.0.2al
Plataforma: Windows 10 64bit, Intel i7, 8GB RAM
Reproduccion del error: 100%
Gravedad: medium

A medida que uno avanza en la partida, el menu se deplaza hacia arriba y desaparece. Hay que llamarlo para volver a ver los comandos.

**Comment by didierrenardub** [comment]
Won't fix. Quizás para el año que viene jaja
