### ISSUE TITLE
Input filter no funciona

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#18]
Proyecto: Python/mines.py
Version: ?
Plataforma: Pc - Windows 10 64b
Gravedad: critical
Titulo:  input filter no funciona.
Descripcion: Al crear un tablero de juego, el input filter de X funciona, el input filter de Y no funciona, ya que permite ingresar numeros negativos y al ingresar una letra crashea.
Paso a paso:
      1.abrir el juego
      2.crear un juego e ingresar un caracter o un numero negativo en el campo Y
      3. el juego crashea
Tasa de reproduccion:100%

**Comment by didierrenardub** [comment]
Este lo marcaría como major porque el valor con el crashea es inesperado. Pero bueno, en este caso la línea entre major y critical es muy delgada...
