### ISSUE TITLE
Al ejecutar el juego, no da ninguna pantalla de inicio

### ISSUE THREAD

**Issue by GaboUB** [didierrenardub/ub_testing#26]
1).- Proyecto: Mines.py
2).- Versión: 1
3).- Plataforma: Windows 10
4).- Escala de la gravedad: Media
5).-Tasa de reproducción: 100%
6).-Título del Bug: Sin pantalla de inicio
7).-Explicación del Bug: Al iniciar el juego, no te da una pantalla inicial,si no hasta el momento de presionar "h" 

![image](https://user-images.githubusercontent.com/38574942/55015824-5638da80-4fcc-11e9-8407-e063843585a5.png)

**Comment by didierrenardub** [comment]
Recordá incluir los pasos para reproducir el problema!
