### ISSUE TITLE
Error al guardar una partida

### ISSUE THREAD

**Issue by GaboUB** [didierrenardub/ub_testing#28]
1).- Proyecto: mines.py
2).- Versión:1
3).- Plataforma: Windows 10
4).- Escala de la gravedad: Media
5).-Tasa de reproducción: 100
6).-Título del Bug: Error al guardar una partida
7).-Explicación del Bug: Cuando intentas guardar una partida, sin tener creado ningún juego, el programa se cierra

**Comment by didierrenardub** [comment]
Quizás lo consideraría de gravedad major, por el hecho de que crashea la aplicación.
