### ISSUE TITLE
Error al mostrar una celda sin juego creado

### ISSUE THREAD

**Issue by GaboUB** [didierrenardub/ub_testing#29]
1).- Proyecto: mines.py
2).- Versión:1
3).- Plataforma: Windows 10
4).- Escala de la gravedad: Media
5).-Tasa de reproducción: 100
6).-Título del Bug: Error al mostrar una celda sin juego creado
7).-Explicación del Bug: Cuando intentas mostrar una celda , sin tener creado un juego, el programa se cierra

**Comment by didierrenardub** [comment]
Mismo caso, lo consideraría de gravedad mayor.
