### ISSUE TITLE
Se rompe al mostrar una celda fuera de los parametros

### ISSUE THREAD

**Issue by GaboUB** [didierrenardub/ub_testing#31]
1).- Proyecto: mines.py
2).- Versión: 1 
3).- Plataforma: Windows 10
4).- Escala de la gravedad: Media
5).-Tasa de reproducción: 100%
6).-Título del Bug: Se rompe al mostrar una celda fuera de los parámetros.
7).-Explicación del Bug: Cuando intentas mostrar una celda fuera de los parámetros del juego iniciado, se rompe el juego y se sale

**Comment by didierrenardub** [comment]
Otro más: gravedad mayor.
