### ISSUE TITLE
Deja iniciar un juego con cero minas

### ISSUE THREAD

**Issue by GaboUB** [didierrenardub/ub_testing#32]
1).- Proyecto: mines.py
2).- Versión: 1
3).- Plataforma: Windows 10
4).- Escala de la gravedad: Minimo
5).-Tasa de reproducción: 100%
6).-Título del Bug: Deja iniciar un juego con cero minas
7).-Explicación del Bug: El juego te deja crear una partida con cero minas

**Comment by didierrenardub** [comment]
Gravedad sería media, en mi opinión!
