### ISSUE TITLE
Flag out of Boundaries

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#33]
Proyecto: Python/mines.py
Version: ?
Plataforma: Pc - Windows 10 64b
Gravedad: critical
Titulo: Flag fuera del tablero crashea
Descripcion: Si se marca una flag afuera del tablero el juego se crashea
Paso a paso:
1.abrir el juego
2.crear un juego con tamaño a eleccion y hacer una flag afuera del tablero
3.crashea
Tasa de reproduccion: 100%

**Comment by didierrenardub** [comment]
En el paso a paso (aplica a todo), es conveniente especificar aún más detalladamente. Por ejemplo:
1) Abrir el juego
2) Crear un juego con tamaño a elección (por ejemplo, game 10 10 10).
3) Intentar mostrar un flag fuera de los límites (por ejemplo, flag 11 11).
4) Notar que el juego crashea.

En este caso, el detalle que agregamos sería sobre los comandos a ejecutar, como para despejar toda duda de cómo se genera el problema.
