### ISSUE TITLE
Sobreposicion Flag-Show

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#34]
Proyecto: Python/mines.py
Version: ?
Plataforma: Pc - Windows 10 64b
Gravedad: critical
Titulo: Sobreposicion Flag-Show
Descripcion: si se muestra una casilla, y se quiere poner una flag en la misma casilla que se mostro el juego lo permite, pero no pone la flag.
Paso a paso:
1.abrir el juego
2.crear un juego con tamaño a eleccion y mostrar una celda y poner una flag en la misma celda que se mostro.
3. el juego permite que se coloque un flag sobre una celda que esta visible ya. Por lo que no coloca la flag pero realiza el metodo
Tasa de reproduccion:100%

**Comment by didierrenardub** [comment]
Lo hubiera marcado como minor o medium porque no impide el desarrollo del juego ni brinda información falsa. Un casillero ya descubierto que no es una bomba no tendría motivos para querer ser marcado!
