### ISSUE TITLE
Elección de opciones no listadas

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#36]
-versión: mines.py v1.0 en windows 10
-La aplicación permite ingresar valores no listados en en menú de las opciones, pero no ocurre nada cuando se ingresa ese valor
-Tasa de reproducción: 100%
-Severidad: Minimal

**Comment by didierrenardub** [comment]
Yo lo pondría como medium, porque puede traer cierta confusión acerca de lo que se quiere hacer y lo que realmente sucede. El usuario puede pensar que algo que escribió produjo algún resultado cuando en realidad no hizo nada.
