### ISSUE TITLE
Admite misma cantidad de minas que coordenadas

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#42]
-versión: mines.py v1.0 en windows 10
-Se pueden ingresar la misma cantidad de minas que coordenadas disponibles
-Tasa de reproducción: 100%
-Severidad: medium

**Comment by didierrenardub** [comment]
Faltó en todos los issues, pero particularmente en este que por su naturaleza no es tan claro es más necesario incluir los pasos a seguir para reproducir el problema.

Yo de todos modos entendí y lo arreglé, pero para que sepas en la próxima ronda!
