### ISSUE TITLE
No se gana, no se pierde

### ISSUE THREAD

**Issue by alehmaub** [didierrenardub/ub_testing#45]
-versión: mines.py v1.0 en windows 10
-No se pierde al pisar una mina, ni se gana al desbloquear todos los espacios libres de minas.
-Tasa de reproducción: 100%
-Severidad: major

**Comment by didierrenardub** [comment]
Ojo que la parte de que no se pierde al pisar una mina queda como duplicado del otro que reportaste acerca de que se puede seguir jugando tras perder:
https://github.com/didierrenardub/ub_testing/issues/43
Te salva, en este caso, que además incluiste que tampoco se gana.
