### ISSUE TITLE
Boundary value analysis failure

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#5]
Proyecto: Python/mines.py
Version: ?
Plataforma: Pc - Windows 10 64b
Gravedad: critical
Titulo: Crashea cuando se ingresa un valor fuera del rango
Descripcion: Al ingresar que muestre una casilla fuera del rango predeterminado se crashea el juego.
Paso a paso: 
	1.Doble click en el archivo
	2.Crear un tablero con el rango deseado
        3.Pedir que se muestre una casilla fuera del rango.
        4.Crash del juego
Tasa de reproduccion: 100%

**Comment by didierrenardub** [comment]
En este caso el título no es de lo más descriptivo; no brinda información de contexto que podría ser útil para identificar el problema sin necesidad de leer el resto de la descripción. Pondría algo más como "Crash al mostrar una casilla fuera de rango". De esa forma ya se sabe de qué trata el bug (crash), usando qué comando (show) y con qué acción (eligiendo una casilla fuera de rango).
