### ISSUE TITLE
Error al tipear otro tamaño de tablero

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#55]
1-Proyecto de la falla encontrada: Buscaminas.
2- Version: Didier reloaded 3.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium/mayor.
5- Tasa de reproduccion: 100%
7- Paso a paso: si despues de seleccionar un tamaño de tablero, se lo modifica a uno mas grande o distinto, aparece un error.

**Comment by didierrenardub** [comment]
Rocío, el paso a paso no es muy claro. Recordá que tiene que ser APB! Por ejemplo:
1) Ejecutar la aplicación
2) Crear un tablero de 20x20 (game 20 20 20)
3) Crear otro tablero de 21x21 (game 21 21 20)
4) Notar que la aplicación muestra un error diciendo...

O sea no es que este caso tenga que ser exactamente así, pero para que te des una idea.

Desgraciadamente, con la información provista no puedo darme cuenta cuál es el problema...
