### ISSUE TITLE
Sin boolean de volver a jugar

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#56]
1-Proyecto de la falla encontrada: Juego Buscaminas.
2- Version: Viernes 22hs
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium/mayor.
5- Tasa de reproduccion: 100%
7- Paso a paso: Al completar el tablero o pegar en una mina, no pregunta si deseo volver a jugar. Finaliza el juego sin dejar ningun mensaje.

**Comment by didierrenardub** [comment]
Mismo caso que en otro de los issues, no comprendo del todo el problema puesto que las instrucciones y descripción no son claras...

**Comment by didierrenardub** [comment]
Ok; no va a preguntar si se desea jugar de nuevo o no por una cuestion de diseño, pero va a dejar un mensaje de que terminó la partida!
