### ISSUE TITLE
buscaminas v4-al perder arma otro juego automaticamente

### ISSUE THREAD

**Issue by diegomoran777** [didierrenardub/ub_testing#64]
Buscaminas:
version 4
sop: windows 10- version:-
Gravedad: critico
Titulo del problema: al perder arma otro juego automaticamente.
Paso a paso: una vez que pierdo el juego me arma un juego automaticamente sin preguntar si quiero uno igualo armar uno de 0. 
Estado del bug: new

**Comment by didierrenardub** [comment]
No lo voy a arreglar; la realidad es que no es un bug, pero no podías saberlo porque no tenés la especificación.
Como el usuario puede dejar la aplicación en cualquier momento usando el comando quit, se optó por automáticamente crear una nueva partida con los mismos parámetros de la última partida creada para fomentar la rejugabilidad.
Por otro lado, no me parece que sea crítico, sino a lo sumo medio o menor.

**Comment by diegomoran777** [comment]
Won t fix jajaja listo

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
