### ISSUE TITLE
Despues de crashear tablero

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#67]
Proyecto: mines.py
Versión: --
Plataforma: windows 10 pro, 64bits
Gravedad: Medium
Descripción: luego de errarle al tamaño de tablero y crashear el juego, al typear de nuevo "help" para pedir el menu y volver a comenzar, dice estas lineas de la imagen.

![image](https://user-images.githubusercontent.com/48370383/55254895-e2026f00-5237-11e9-98d7-fc1992b36e93.png)

**Comment by didierrenardub** [comment]
No es un bug; eso es porque se queda en la línea de comando de Python, porque lo ejecutaste desde IDLE (un entorno de programación). Ejecutarlo desde consola no provoca este comportamiento.
