### ISSUE TITLE
Seleccion "help","copyright", "license", "credits"

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#68]
Proyecto: mines.py
Versión: antes de las 17.30hs
Plataforma: windows 10 pro, 64bits
Gravedad: Medium
Descripción: al seleccionar cada opcion de menu "help","copyright", "license", "credits" indica informacion, luego al volver a seleccionar "help", aparece cartel que se encuentra en la imagen sin dar señales del menu oculto.

![image](https://user-images.githubusercontent.com/48370383/55255040-4de4d780-5238-11e9-87e4-98d9b599cb4d.png)

**Comment by didierrenardub** [comment]
Not a bug; eso no pertenece al juego sino a Python. En la captura no se ve el juego en ejecución.
