### ISSUE TITLE
Cargar partida

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#71]
Proyecto: mines.py
Versión: --
Plataforma: Windows 10 pro, 64bits
Gravedad: Medium
Descripción: Al cargar una partida, el tablero empieza como si recien se iniciara el juego, sin ningun movimiento, en 0 completamente.

![image](https://user-images.githubusercontent.com/48370383/55255836-50e0c780-523a-11e9-9476-324150dd957c.png)

**Comment by didierrenardub** [comment]
El título del bug no es descriptivo del problema, tenelo en cuenta para futuros reportes!
