### ISSUE TITLE
Sin nivel de dificultad, Flags infinitos, No descuenta Tiempo ni flags restantes

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#72]
Proyecto: mines.py
Versión: --
Plataforma: Windows 10 pro, 64bits
Gravedad: Medium
Descripción: al iniciar el juego no hay reloj para descontar el tiempo. No pregunta nivel de dificultad. Los flags son practicamente infinitos. No muestra cuantos flags tiene en total y en caso de usarlos cuantos quedan. 

![image](https://user-images.githubusercontent.com/48370383/55256407-c9945380-523b-11e9-9fe4-c720d3c9eb0a.png)

**Comment by didierrenardub** [comment]
Nivel de dificultad lo regula uno al crear la partida; tiempo no hay por cuestiones técnicas, pero sí arreglé lo del conteo de flags!
