### ISSUE TITLE
Sin opciones

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#76]
Proyecto: mines.py
Versión: --
Plataforma: Windows 10 pro, 64bits
Gravedad: Medium
Descripción: no da ningun tipo de opcion de nada, por ejemplo, activar o no el sonido, o tiempo o desactivar los flags.

**Comment by didierrenardub** [comment]
No lo voy a arreglar; sonido no va a tener, tiempo tampoco, los flags son parte del juego, una ayuda para el usuario, que si quiere no los usa!
