### ISSUE TITLE
Sin estadisticas

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#77]
Proyecto: mines.py
Versión: null
Plataforma: Windows 10 pro, 64bits
Gravedad: Medium
Descripción: no muestra porcentaje de victorias, ni numero de partidas realizadas, ni mayor racha de perdidas/victorias.

**Comment by didierrenardub** [comment]
Por una cuestión de tiempo, sólo voy a poner ganadas y perdidas desde que se ejecutó la aplicación!
