### ISSUE TITLE
Mines Overload

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#8]
Proyecto: Python/mines.py
Version: ?
Plataforma: Pc - Windows 10 64b
Gravedad:  critical
Titulo: Sobrecarga de minas causa crash del juego
Descripcion: Si se marcan mas minas que lugares disponibles en el tablero se crashea el juego
Paso a paso:
       1.abrir el juego
       2.crear un juego con tamaño a eleccion y crear mas minas que lugares
       3.crashea
Tasa de reproduccion:

**Comment by didierrenardub** [comment]
Acá hay que marcar una pequeña diferencia: cuando una aplicación crashea, la misma detiene la ejecución. El comportamiento que se experimenta en esta falla es un freeze, porque la aplicación deja de responder pero se mantiene activa.

Y faltó aclarar la tasa de reproducción!
