### ISSUE TITLE
Despues de perder, inicia un juego automaticamente sin preguntar

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#81]
1-Proyecto de la falla encontrada: Buscaminas.
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso: Al perder un juego, inicia otro automaticamente, dando por hecho que el usuario quiere continuar jugando. No pregunta si se quiere volver a jugar o no. 

![image](https://user-images.githubusercontent.com/48370383/55263963-8ba22a00-5251-11e9-9c2b-5ae51377b6e1.png)

**Comment by didierrenardub** [comment]
Won't fix. Siendo que el usuario puede elegir salir en cualquier momento, el hecho de reiniciar una nueva partida es para comodidad del usuario.
