### ISSUE TITLE
Poner minas Negativas

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#85]
Proyecto: Python/mines.py
Version: 2
Plataforma: Pc - Windows 10 64b
Gravedad: Medium
Descripcion: Al ingresar un numero negativo en la cantidad de minas, lo considera como un numero menor a la cantidad minima  de minas necesarias para jugar. En vez de tomarlo como un error de input
Paso a paso:
1.Abrir el juego
2.Crear un tablero de cualquier tamaño
3.Poner un numero negativo de minas
4.Aparece un cartel de que las minas son menores a las necesarias pero no tira el error de error de input.
Tasa de reproduccion: 100%

**Comment by didierrenardub** [comment]
No me parece que sea de gravedad media; siendo que número negativo de minas es menor que las permitidas, se considera que está cubierto con ese caso y por ende no lo voy a arreglar.

**Comment by didierrenardub** [comment]
Lo vuelvo a cerrar, queda como que no va a ser reparado.
