### ISSUE TITLE
Espacios en blanco 

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#89]
1-Proyecto de la falla encontrada: Buscaminas.
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso:  no puede haber espacios en blanco al iniciar el juego, deben aparecer numeros para deducir donde se encuentra la mina.

![image](https://user-images.githubusercontent.com/48370383/55266925-29035b00-525e-11e9-9d53-89da642372d0.png)

**Comment by didierrenardub** [comment]
Not a bug. En todos los buscaminas hay espacios en blanco.
