### ISSUE TITLE
Crash al guardar partida. Se cierra de forma inesperada

### ISSUE THREAD

**Issue by rocarp29** [didierrenardub/ub_testing#92]
1-Proyecto de la falla encontrada: Buscaminas.
2- Version: 2.0
3-Sistema operativo: Windows 10 pro.
4- Gravedad del bug: medium
5- Tasa de reproduccion: 100%
7- Paso a paso:  Creo un tablero. Juego un poco, quiero guardarlo, se cierra de forma inesperada.

**Comment by didierrenardub** [comment]
Hola Rocío,

Desgraciadamente no pude reproducir la falla. Podrías agregar más detalle?

Gracias!
