### ISSUE TITLE
Primer toque se pierde

### ISSUE THREAD

**Issue by federicofranco97** [didierrenardub/ub_testing#98]
Proyecto: Python/mines.py
Version: 3
Plataforma: Pc - Windows 10 64b
Gravedad: Medium
Descripcion: Hay posibilidad de que el primer toque que haga el usuario sea a sobre una mina y se pierda el juego.
Paso a paso:
1.Abrir el juego
2.Crear un juego de tamaño y minas a eleccion
3.Tocar en cualquier lado (tiene la chance de que toque sobre una mina. )
4.Para aumentar la posibilidad de que esto pase crear un tablero con la maxima cantidad de minas, guardarlo, y seguir intentando que el primer toque sea una mina sobre el tablero que se carga. De esta manera se puede hacer un metodo de descarte de coordenadas hasta que se descubre una mina.

Tasa de reproduccion: 100%

**Comment by didierrenardub** [comment]
Won't fix, usaremos las reglas del buscaminas original!
